baseURL = 'https://journal.littlegiving.org/'
canonifyurls = true
languageCode = 'en-gb'
title = 'Little Giving Journal'
theme = ['littlegiving']
disableKinds = ["home", "taxonomy", "term"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  posts = '/:filename'